# https://nixos.wiki/wiki/Nix_on_Travis
language: nix
cache:
  directories:
  - $HOME/nix.store
os: linux
dist: bionic

addons:
  apt:
    packages:
      - haskell-stack

before_install:
  - sudo mkdir -p /etc/nix
  - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
  - export DIR=~/.local/bin
  - if [ ! -d "$DIR" ]; then mkdir -p $DIR; fi
  - export PATH=~/.local/bin:$PATH
  - travis_retry eval $"stack upgrade"
  - hash -r
  - stack --version

before_cache:
  - mkdir -p $HOME/nix.store
  - nix copy --to file://$HOME/nix.store -f default.nix buildInputs

before_script:
  - sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

script:
  - make build
